import { SearchAndFilterContextActions } from '@/types/contexts/search-and-filter-context';

const actions: SearchAndFilterContextActions = {
  CHANGE_SEARCH_QUERY: 'CHANGE_SEARCH_QUERY',
  CHANGE_PAGE: 'CHANGE_PAGE',
  CHANGE_MIN_DURATION: 'CHANGE_MIN_DURATION',
  CHANGE_MAX_DURATION: 'CHANGE_MAX_DURATION',
  CHANGE_START_DATE: 'CHANGE_START_DATE',
  CHANGE_END_DATE: 'CHANGE_END_DATE',
  CHANGE_LANGUAGE_ID: 'CHANGE_LANGUAGE_ID',
  CHANGE_GENRE_IDS: 'CHANGE_GENRE_IDS',
  CHANGE_LOADING_STATE: 'CHANGE_LOADING_STATE',
  SAVE_MOVIES: 'SAVE_MOVIES',
};

export default actions;
